#!/usr/bin/env bash
# Displays numbers from 1 to 100 in list format.
#   Displays "Fizz" when the number is a multiple of 3.
#   Displays "FizzBuzz" when the number is a multiple of 3 and 5.
#   Otherwise, displays the number.
#   Displays "Buzz" when the number is a multiple of 5.

for a_num in {1..100}
do
  if (( a_num % 3 == 0 && a_num % 5 == 0 ))
  then
    echo "FizzBuzz"
  elif (( a_num % 3 == 0 ))
  then
    echo "Fizz"
  elif (( a_num % 5 == 0 ))
  then
    echo "Buzz"
  else
    echo "$a_num"
  fi
done
