#!/usr/bin/env bash

for a_num in {1..100}
do
  if (( a_num % 3 == 0 && a_num % 5 == 0 ))
  then
    echo "FizzBuzz"
  elif (( a_num % 3 == 0 ))
  then
    echo "Fizz"
  elif (( a_num % 5 == 0 ))
  then
    echo "Buzz"
  else
    echo "$a_num"
  fi
done
