#!/usr/bin/env bash
# Displays numbers from 1 to 20 in addition to:
#   "bad luck from Japan" for the 9th iteration
#   "bad luck from Italy" for the 17th loop iteration
#   "bad luck from China" for the 4th iteration

poll=1

while [ $poll -le 20 ]
do
  echo "$poll"
  case $poll in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( poll++ ))
done
