#!/usr/bin/env bash
# Prints the contents of the current directory in list format.
#   Only prints the part of the name after the first dash. 

lst=$(ls)
for x in $lst; do
  echo "$x" | cut -d '-' -f2
done
